const fs = require('fs');
let c = fs.readFileSync('src/utils/translations.ts', 'utf8');

c = c.replace(/        common: \{/g, '        common: {\n            generated_by: "Generated by Nagarsevak Management System",');
c = c.replace(/            generated_by: "Generated by Nagarsevak Management System",\n            title: "डॅशबोर्ड",/g, '            generated_by: "नगरसेवक व्यवस्थापन प्रणाली द्वारे तयार केले",\n            title: "डॅशबोर्ड",');

fs.writeFileSync('src/utils/translations.ts', c);
console.log('Added generated_by');
