-- Create table for Scheme Applications
create table if not exists public.scheme_applications (
  id bigint generated by default as identity primary key,
  scheme_id bigint references public.schemes(id),
  voter_id bigint references public.voters(id), -- Optional link to voter
  applicant_name text not null,
  mobile text,
  address text,
  notes text,
  status text default 'Pending', -- Pending, Approved, Rejected
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table public.scheme_applications enable row level security;

-- Create policy to allow all actions for now (since we are in an admin app context)
create policy "Enable all access for all users" on public.scheme_applications
for all using (true) with check (true);
