const fs = require('fs');

let c = fs.readFileSync('src/utils/translations.ts', 'utf8');

// 1. Correct en.common.generated_by and add report_columns to en.common
// Let's find:
//     en: {
//         common: {
//             generated_by: "नगरसेवक व्यवस्थापन प्रणाली द्वारे तयार केले",
//             welcome: "Welcome",
// we replace it with:
//     en: {
//         common: {
//             generated_by: "Generated by Nagarsevak Management System",
//             report_columns: {
//                 sr_no: "Sr No",
//                 date_time: "Date & Time",
//                 date: "Date",
//                 citizen_info: "Citizen Info",
//                 title_type: "Title / Type",
//                 location_area: "Location / Area",
//                 staff: "Staff",
//                 status: "Status",
//                 mobile: "Mobile",
//                 area: "Area",
//                 scheme_name: "Scheme Name",
//                 description: "Description",
//                 category: "Category",
//                 benefits: "Benefits",
//                 thumbnail: "Thumbnail",
//                 title_desc: "Title / Description",
//                 type: "Type",
//                 amount: "Amount"
//             },
//             welcome: "Welcome",

c = c.replace(
    /en:\s*\{\r?\n\s*common:\s*\{\r?\n\s*generated_by:\s*"नगरसेवक व्यवस्थापन प्रणाली द्वारे तयार केले",\r?\n\s*welcome:\s*"Welcome",/,
    'en: {\n        common: {\n            generated_by: "Generated by Nagarsevak Management System",\n            report_columns: {\n                sr_no: "Sr No",\n                date_time: "Date & Time",\n                date: "Date",\n                citizen_info: "Citizen Info",\n                title_type: "Title / Type",\n                location_area: "Location / Area",\n                staff: "Staff",\n                status: "Status",\n                mobile: "Mobile",\n                area: "Area",\n                scheme_name: "Scheme Name",\n                description: "Description",\n                category: "Category",\n                benefits: "Benefits",\n                thumbnail: "Thumbnail",\n                title_desc: "Title / Description",\n                type: "Type",\n                amount: "Amount"\n            },\n            welcome: "Welcome",'
);

// 2. Add amount: "रक्कम" and generated_by: "नगरसेवक..." to mr.common
// Let's find:
//     mr: {
//         common: {
//             report_columns: {
//                 sr_no: "अ. क्र.",
//                 date_time: "दिनांक आणि वेळ",
//                 date: "दिनांक",
//                 citizen_info: "नागरिकांची माहिती",
//                 title_type: "शीर्षक / प्रकार",
//                 location_area: "ठिकाण / भाग",
//                 staff: "कर्मचारी",
//                 status: "स्थिती",
//                 mobile: "मोबाईल",
//                 area: "भाग",
//                 scheme_name: "योजनेचे नाव",
//                 description: "वर्णन",
//                 category: "श्रेणी",
//                 benefits: "फायदे",
//                 thumbnail: "थंबनेल",
//                 title_desc: "शीर्षक / वर्णन",
//                 type: "प्रकार"
//             },
//             welcome: "स्वागत आहे",

c = c.replace(
    /mr:\s*\{\r?\n\s*common:\s*\{\r?\n\s*report_columns:\s*\{\r?\n\s*sr_no:\s*"अ. क्र.",\r?\n\s*date_time:\s*"दिनांक आणि वेळ",\r?\n\s*date:\s*"दिनांक",\r?\n\s*citizen_info:\s*"नागरिकांची माहिती",\r?\n\s*title_type:\s*"शीर्षक \/ प्रकार",\r?\n\s*location_area:\s*"ठिकाण \/ भाग",\r?\n\s*staff:\s*"कर्मचारी",\r?\n\s*status:\s*"स्थिती",\r?\n\s*mobile:\s*"मोबाईल",\r?\n\s*area:\s*"भाग",\r?\n\s*scheme_name:\s*"योजनेचे नाव",\r?\n\s*description:\s*"वर्णन",\r?\n\s*category:\s*"श्रेणी",\r?\n\s*benefits:\s*"फायदे",\r?\n\s*thumbnail:\s*"थंबनेल",\r?\n\s*title_desc:\s*"शीर्षक \/ वर्णन",\r?\n\s*type:\s*"प्रकार"\r?\n\s*\},\r?\n\s*welcome:\s*"स्वागत आहे",/,
    'mr: {\n        common: {\n            generated_by: "नगरसेवक व्यवस्थापन प्रणाली द्वारे तयार केले",\n            report_columns: {\n                sr_no: "अ. क्र.",\n                date_time: "दिनांक आणि वेळ",\n                date: "दिनांक",\n                citizen_info: "नागरिकांची माहिती",\n                title_type: "शीर्षक / प्रकार",\n                location_area: "ठिकाण / भाग",\n                staff: "कर्मचारी",\n                status: "स्थिती",\n                mobile: "मोबाईल",\n                area: "भाग",\n                scheme_name: "योजनेचे नाव",\n                description: "वर्णन",\n                category: "श्रेणी",\n                benefits: "फायदे",\n                thumbnail: "थंबनेल",\n                title_desc: "शीर्षक / वर्णन",\n                type: "प्रकार",\n                amount: "रक्कम"\n            },\n            welcome: "स्वागत आहे",'
);

fs.writeFileSync('src/utils/translations.ts', c);
console.log('Successfully updated translations.ts');
