const fs = require('fs');

let c = fs.readFileSync('src/utils/translations.ts', 'utf8');

// 1. Add generated_by to MR common
c = c.replace(
    /        common: \{\s*\n/,
    '        common: {\n            generated_by: "नगरसेवक व्यवस्थापन प्रणाली द्वारे तयार केले",\n'
);

// 2. Add generated_by to EN common
c = c.replace(
    /export const translations = \{\n    en: \{\n        common: \{\s*\n/,
    'export const translations = {\n    en: {\n        common: {\n            generated_by: "Generated by Nagarsevak Management System",\n'
);

// 3. Add schemes keys to MR schemes
// The MR block starts with '        schemes: {' inside 'mr: {'
// Let's replace the first title: "सरकारी योजना" in the file which is in MR.
c = c.replace(
    /        schemes: \{\s*\n\s*title: "सरकारी योजना",/g,
    '        schemes: {\n            applicant_name: "अर्जदाराचे नाव",\n            mobile_address: "मोबाईल / पत्ता",\n            benefit_reason: "लाभ / कारण",\n            application_report: "अर्ज अहवाल",\n            total_applications: "एकूण अर्ज",\n            pdf_error: "PDF तयार करण्यात त्रुटी. कृपया पुन्हा प्रयत्न करा.",\n            title: "सरकारी योजना",'
);

// 4. Add schemes keys to EN schemes
c = c.replace(
    /        schemes: \{\s*\n\s*title: "Government Schemes",/g,
    '        schemes: {\n            applicant_name: "Applicant Name",\n            mobile_address: "Mobile / Address",\n            benefit_reason: "Benefit / Reason",\n            application_report: "Application Report",\n            total_applications: "Total Applications",\n            pdf_error: "Failed to generate PDF. Please try again.",\n            title: "Government Schemes",'
);

// 5. Add assign_info to MR tasks
c = c.replace(
    /        tasks: \{\s*\n\s*title: "कामे",/g,
    '        tasks: {\n            assign_info: "नेमलेले व्यक्ती",\n            title: "कामे",'
);

// 6. Translate communication_page in MR
// We replace 'conf_meet_link: "Meeting Link"' and 'conf_signature: "Signature"' in MR communication_page
// To be safe, we will just look for 'title: "जनसंवाद"' and replace the previous lines.
c = c.replace(
    /            conf_meet_link: "Meeting Link",\s*\n\s*conf_signature: "Signature",\s*\n\s*title: "जनसंवाद",/g,
    '            conf_meet_link: "मीटिंग लिंक",\n            conf_signature: "स्वाक्षरी",\n            title: "जनसंवाद",'
);

fs.writeFileSync('src/utils/translations.ts', c);
console.log('Translations restored and added successfully!');
