-- Create table for tracking Event RSVPs
CREATE TABLE IF NOT EXISTS public.event_rsvps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id bigint REFERENCES public.events(id) ON DELETE CASCADE,
    voter_id bigint REFERENCES public.voters(id) ON DELETE SET NULL, -- Link to voters table
    status text CHECK (status IN ('Yes', 'No', 'Maybe', 'Pending')) DEFAULT 'Pending',
    response_source text DEFAULT 'WhatsApp', -- e.g. 'WhatsApp', 'Manual'
    created_at timestamptz DEFAULT timezone('utc'::text, now()),
    
    -- Ensure one RSVP per voter per event
    UNIQUE(event_id, voter_id)
);

-- Enable RLS
ALTER TABLE public.event_rsvps ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for authenticated users" ON public.event_rsvps FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Enable insert access for authenticated users" ON public.event_rsvps FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update access for authenticated users" ON public.event_rsvps FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete access for authenticated users" ON public.event_rsvps FOR DELETE USING (auth.role() = 'authenticated');

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_event_rsvps_event_id ON public.event_rsvps(event_id);
