-- Create table for App Settings (Single Row Pattern)
create table if not exists app_settings (
  id bigint generated by default as identity primary key,
  nagarsevak_name_english text,
  nagarsevak_name_marathi text,
  ward_name text,
  ward_number text,
  party_name text,
  party_logo_url text,
  profile_image_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table app_settings enable row level security;

-- Policies
drop policy if exists "Allow public read app_settings" on app_settings;
create policy "Allow public read app_settings" on app_settings for select to anon, authenticated using (true);

drop policy if exists "Allow auth update app_settings" on app_settings;
create policy "Allow auth update app_settings" on app_settings for update to authenticated using (true);

drop policy if exists "Allow auth insert app_settings" on app_settings;
create policy "Allow auth insert app_settings" on app_settings for insert to authenticated with check (true);

-- Functions to ensure single row
CREATE OR REPLACE FUNCTION initialize_app_settings() 
RETURNS void AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM app_settings LIMIT 1) THEN
    INSERT INTO app_settings (nagarsevak_name_english, ward_name) 
    VALUES ('Nagar Sevak', 'Ward No. 1');
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Run initialization
SELECT initialize_app_settings();
