-- Create table for Non-Voters
create table if not exists non_voters (
  id bigint generated by default as identity primary key,
  name text,
  mobile text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table non_voters enable row level security;

-- Policies
create policy "Allow public insert non_voters" on non_voters for insert to anon with check (true);
create policy "Allow public read non_voters" on non_voters for select to anon using (true);
create policy "Allow public update non_voters" on non_voters for update to anon using (true);

-- Allow public to update voters (for mobile number sync)
create policy "Allow public update voters" on voters for update to anon using (true);
