-- Create ward_provisions table to track requests and sanctions
CREATE TABLE IF NOT EXISTS ward_provisions (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    requested_amount numeric not null,
    sanctioned_amount numeric,
    requested_date date default current_date,
    sanctioned_date date,
    status text default 'Pending', -- Pending, Approved, Rejected, Partially Approved
    financial_year text,
    category text, -- Road, Water, drainage, etc.
    letter_reference text, -- Letter No / File ID
    metadata jsonb, -- For area, department, etc.
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE ward_provisions ENABLE ROW LEVEL SECURITY;

-- Policies (matching standard anon access for this app)
CREATE POLICY "Allow public read ward_provisions" ON ward_provisions FOR SELECT TO anon USING (true);
CREATE POLICY "Allow public insert ward_provisions" ON ward_provisions FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow public update ward_provisions" ON ward_provisions FOR UPDATE TO anon USING (true);
