-- Create a table for Social Media Posts
create table if not exists social_posts (
  id bigint generated by default as identity primary key,
  platform text check (platform in ('Facebook', 'Instagram')),
  external_id text unique,
  content text,
  media_url text, -- Link to image/video
  permalink text, -- Link to original post
  likes_count integer default 0,
  comments_count integer default 0,
  shares_count integer default 0,
  posted_at timestamp with time zone not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table social_posts enable row level security;

-- Policies
create policy "Allow public read social" on social_posts for select to anon using (true);
create policy "Allow public insert social" on social_posts for insert to anon with check (true);
