-- Create table for Non-Voters
create table if not exists non_voters (
  id bigint generated by default as identity primary key,
  name text,
  mobile text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for non_voters
alter table non_voters enable row level security;
create policy "Allow public insert non_voters" on non_voters for insert to anon with check (true);
create policy "Allow public read non_voters" on non_voters for select to anon using (true);
create policy "Allow public update non_voters" on non_voters for update to anon using (true);

-- Allow public to update voters (for mobile number sync)
create policy "Allow public update voters" on voters for update to anon using (true);

-- Add category to complaints
alter table complaints 
add column if not exists category text default 'Complaint'; -- 'Complaint' or 'Help'

-- Create table for Party Members (Sadasya)
create table if not exists party_members (
  id bigint generated by default as identity primary key,
  name text not null,
  mobile text not null,
  age integer,
  address text,
  is_voter boolean default false,
  voter_id text, -- Link to voter table if needed
  registered_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for party_members
alter table party_members enable row level security;
create policy "Allow public insert party_members" on party_members for insert to anon with check (true);
create policy "Allow staff read party_members" on party_members for select to authenticated using (true);
