-- 1. Create table (Safe to run multiple times)
create table if not exists non_voters (
  id bigint generated by default as identity primary key,
  name text,
  mobile text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
alter table non_voters enable row level security;

-- 3. Policies (Drop first to avoid "already exists" error)
drop policy if exists "Allow public insert non_voters" on non_voters;
create policy "Allow public insert non_voters" on non_voters for insert to anon with check (true);

drop policy if exists "Allow public read non_voters" on non_voters;
create policy "Allow public read non_voters" on non_voters for select to anon using (true);

drop policy if exists "Allow public update non_voters" on non_voters;
create policy "Allow public update non_voters" on non_voters for update to anon using (true);

drop policy if exists "Allow public update voters" on voters;
create policy "Allow public update voters" on voters for update to anon using (true);

-- 4. Add category column (Safe)
alter table complaints 
add column if not exists category text default 'Complaint';
