-- Create a table for Voters
create table if not exists voters (
  id bigint generated by default as identity primary key,
  epic_no text, 
  name_marathi text,
  name_english text,
  relation_name_marathi text,
  relation_name_english text,
  relation_type text,
  house_no text,
  age integer,
  gender text,
  address_marathi text,
  address_english text,
  ac_no integer,
  part_no integer,
  serial_no text, -- Sometimes serials have chars
  new_serial_no integer,
  mobile text,
  ward_no text,
  caste text,
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table voters enable row level security;

-- Policies
create policy "Allow public read voters" on voters for select to anon using (true);
create policy "Allow public insert voters" on voters for insert to anon with check (true);
