-- Create Schems Table
create table if not exists schemes (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  eligibility text,
  benefits text,
  documents text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table schemes enable row level security;
create policy "Allow public read schemes" on schemes for select to anon using (true);
create policy "Allow public insert schemes" on schemes for insert to anon with check (true); -- For seeding

-- Update Complaints to link scheme
alter table complaints 
add column if not exists scheme_id bigint references schemes(id);

-- Insert Sample Data (Maharashtra Context)
insert into schemes (name, description, eligibility, benefits, documents)
values 
('Majhi Ladki Bahin Yojana', 'Financial assistance for women in Maharashtra.', 'Women aged 21-65, Income < 2.5L/year', '₹1500 per month', 'Aadhar, Ration Card, Bank Passbook'),
('PM Vishwakarma Yojana', 'Support for traditional artisans and craftspeople.', 'Artisans aged 18+, Traditional Trade', 'Loan up to ₹3L at 5%, Skill Training', 'Aadhar, Skill Certificate'),
('Lek Ladki Yojana', 'Financial assistance for girl child.', 'Yellow/Orange Ration Card holders', 'Total ₹1 Lakh till age 18', 'Birth Certificate, Income Proof');
