-- Create a table for Complaints
create table if not exists complaints (
  id bigint generated by default as identity primary key,
  user_id text, -- WhatsApp Number
  user_name text,
  problem text,
  location text,
  status text default 'Pending',
  source text default 'Web',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table complaints enable row level security;

-- Policy: Allow everyone to insert (for anon users via Bot/Web)
create policy "Allow public insert"
on complaints for insert
to anon
with check (true);

-- Policy: Allow everyone to read (for Admin dashboard)
create policy "Allow public read"
on complaints for select
to anon
using (true);
