-- Create improvements table for citizen suggestions
CREATE TABLE IF NOT EXISTS improvements (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    location text,
    area text,
    status text default 'Proposed', -- Proposed, Approved, Rejected
    completion_date date, -- Expected completion if approved
    votes integer default 0,
    metadata jsonb, -- For people_benefited and other metrics
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE improvements ENABLE ROW LEVEL SECURITY;

-- Policies
DROP POLICY IF EXISTS "Allow public read improvements" ON improvements;
CREATE POLICY "Allow public read improvements" ON improvements FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Allow public insert improvements" ON improvements;
CREATE POLICY "Allow public insert improvements" ON improvements FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update improvements" ON improvements;
CREATE POLICY "Allow public update improvements" ON improvements FOR UPDATE TO anon USING (true);
