-- Create Works Table
create table if not exists works (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  location text,
  status text default 'Completed', -- Planned, InProgress, Completed
  completion_date date,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Events Table
create table if not exists events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  event_date date,
  event_time time,
  location text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table works enable row level security;
create policy "Allow public read works" on works for select to anon using (true);
create policy "Allow public insert works" on works for insert to anon with check (true);

alter table events enable row level security;
create policy "Allow public read events" on events for select to anon using (true);
create policy "Allow public insert events" on events for insert to anon with check (true);
