-- ==============================================================================
-- RESTORE COMPLAINTS TABLE, PERMISSIONS & RELOAD SCHEMA CACHE
-- Run this script in your Supabase SQL Editor (Dashboard -> SQL Editor -> New Query -> Run)
-- ==============================================================================

-- 1. Ensure complaints table exists with all required columns
CREATE TABLE IF NOT EXISTS public.complaints (
    id bigint generated by default as identity primary key,
    user_id text,
    user_name text,
    problem text,
    location text,
    status text default 'Pending',
    source text default 'Web',
    category text default 'Complaint',
    priority text default 'Medium',
    voter_id text,
    image_url text,
    video_url text,
    assigned_to text,
    area text,
    description_meta jsonb,
    tenant_id uuid references public.tenants(id) on delete set null,
    estimated_completion_date date,
    plan text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ensure all columns exist
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS user_id text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS user_name text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS problem text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS location text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS status text DEFAULT 'Pending';
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS source text DEFAULT 'Web';
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS category text DEFAULT 'Complaint';
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS priority text DEFAULT 'Medium';
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS voter_id text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS video_url text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS assigned_to text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS area text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS description_meta jsonb;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS tenant_id uuid REFERENCES public.tenants(id) ON DELETE SET NULL;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS estimated_completion_date date;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS plan text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT timezone('utc'::text, now());

-- 2. Grant table and sequence permissions to public & authenticated roles
GRANT ALL ON TABLE public.complaints TO postgres, anon, authenticated, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- 3. Enable RLS and setup permissive policies for tenant isolation
ALTER TABLE public.complaints ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Tenant Isolation Select" ON public.complaints;
DROP POLICY IF EXISTS "Allow public read" ON public.complaints;
CREATE POLICY "Tenant Isolation Select" ON public.complaints 
    FOR SELECT 
    USING (
        tenant_id IN (SELECT tenant_id FROM public.user_tenant_mapping WHERE user_id = auth.uid())
        OR auth.role() = 'anon'
        OR auth.role() = 'service_role'
        OR tenant_id IS NULL
    );

DROP POLICY IF EXISTS "Tenant Isolation Insert" ON public.complaints;
DROP POLICY IF EXISTS "Allow public insert" ON public.complaints;
CREATE POLICY "Tenant Isolation Insert" ON public.complaints 
    FOR INSERT 
    WITH CHECK (
        tenant_id IN (SELECT tenant_id FROM public.user_tenant_mapping WHERE user_id = auth.uid())
        OR auth.role() = 'anon'
        OR auth.role() = 'service_role'
        OR tenant_id IS NOT NULL
    );

DROP POLICY IF EXISTS "Tenant Isolation Update" ON public.complaints;
CREATE POLICY "Tenant Isolation Update" ON public.complaints 
    FOR UPDATE 
    USING (
        tenant_id IN (SELECT tenant_id FROM public.user_tenant_mapping WHERE user_id = auth.uid())
        OR auth.role() = 'service_role'
    );

DROP POLICY IF EXISTS "Tenant Isolation Delete" ON public.complaints;
CREATE POLICY "Tenant Isolation Delete" ON public.complaints 
    FOR DELETE 
    USING (
        tenant_id IN (SELECT tenant_id FROM public.user_tenant_mapping WHERE user_id = auth.uid())
        OR auth.role() = 'service_role'
    );

-- 4. Backfill any existing unassigned complaints to Krishnaniti demo tenant
UPDATE public.complaints 
SET tenant_id = 'bf4c7152-6006-41b5-9c7d-84c76ea67da4' 
WHERE tenant_id IS NULL;

-- 5. Force PostgREST to reload its schema cache immediately
NOTIFY pgrst, 'reload schema';
NOTIFY pgrst, 'reload config';
