-- Create Support Tickets Table
CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE,
    category TEXT,
    plan TEXT,
    user_id TEXT, -- User email
    user_name TEXT, -- User name
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    priority TEXT DEFAULT 'Medium',
    status TEXT DEFAULT 'Pending',
    description_meta JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

-- Trigger to automatically populate tenant details (category & plan)
DROP TRIGGER IF EXISTS trg_populate_details_support_tickets ON public.support_tickets;
CREATE TRIGGER trg_populate_details_support_tickets 
BEFORE INSERT OR UPDATE ON public.support_tickets 
FOR EACH ROW EXECUTE FUNCTION populate_record_tenant_details();

-- RLS Policies: Tenant Isolation
DROP POLICY IF EXISTS "Tenant Isolation Select" ON public.support_tickets;
CREATE POLICY "Tenant Isolation Select" ON public.support_tickets FOR SELECT USING (
    (tenant_id = (SELECT tenant_id FROM public.user_tenant_mapping WHERE user_id = auth.uid())
     AND category = (SELECT UPPER(tier) FROM public.tenants WHERE id = tenant_id)
     AND plan = (SELECT UPPER(plan) FROM public.tenants WHERE id = tenant_id))
    OR
    EXISTS (SELECT 1 FROM public.user_tenant_mapping WHERE user_id = auth.uid() AND role = 'super_admin')
);

DROP POLICY IF EXISTS "Tenant Isolation Insert" ON public.support_tickets;
CREATE POLICY "Tenant Isolation Insert" ON public.support_tickets FOR INSERT WITH CHECK (
    (tenant_id = (SELECT tenant_id FROM public.user_tenant_mapping WHERE user_id = auth.uid()))
    OR
    EXISTS (SELECT 1 FROM public.user_tenant_mapping WHERE user_id = auth.uid() AND role = 'super_admin')
);

DROP POLICY IF EXISTS "Tenant Isolation Update" ON public.support_tickets;
CREATE POLICY "Tenant Isolation Update" ON public.support_tickets FOR UPDATE USING (
    (tenant_id = (SELECT tenant_id FROM public.user_tenant_mapping WHERE user_id = auth.uid())
     AND category = (SELECT UPPER(tier) FROM public.tenants WHERE id = tenant_id)
     AND plan = (SELECT UPPER(plan) FROM public.tenants WHERE id = tenant_id))
    OR
    EXISTS (SELECT 1 FROM public.user_tenant_mapping WHERE user_id = auth.uid() AND role = 'super_admin')
);

DROP POLICY IF EXISTS "Tenant Isolation Delete" ON public.support_tickets;
CREATE POLICY "Tenant Isolation Delete" ON public.support_tickets FOR DELETE USING (
    (tenant_id = (SELECT tenant_id FROM public.user_tenant_mapping WHERE user_id = auth.uid())
     AND category = (SELECT UPPER(tier) FROM public.tenants WHERE id = tenant_id)
     AND plan = (SELECT UPPER(plan) FROM public.tenants WHERE id = tenant_id))
    OR
    EXISTS (SELECT 1 FROM public.user_tenant_mapping WHERE user_id = auth.uid() AND role = 'super_admin')
);
